weights: /content/drive/MyDrive/Veg_dtect/yolov5/runs/train/exp5/weights/last.pt
cfg: ''
data: /content/Food-Dataset-6/data.yaml
hyp:
  lr0: 0.001
  lrf: 0.001
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
epochs: 40
batch_size: 16
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: drive/MyDrive/Veg_dtect/yolov5/data/hyps
resume_evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: Adam
sync_bn: false
workers: 8
project: drive/MyDrive/Veg_dtect/yolov5/runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 7
freeze:
- 0
save_period: -1
seed: 42
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: drive/MyDrive/Veg_dtect/yolov5/runs/train/exp5
